[project]
name = "plm-Blast"
version = "0.0.2"
authors = [
  { name="Stanisław Dunin-Horkawicz", email="s.dunin-horkawicz@cent.uw.edu.pl" },
  { name="Kamil Kamiński", email="k.kaminski16@uw.edu.pl"}
]
description = "plm-Blast package a tool for aligning sequence based language model potein representation"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "Bio==1.5.9",
    "matplotlib==3.7.1",
    "numba==0.57.1",
    "pandas==2.0.2",
    "numpy==1.24.3",
    "scikit_learn==1.2.2",
    "torch==2.0.1",
    "tqdm",
    "transformers>=4.38.0",
    "sentencepiece==0.1.99",
    "psutil",
    "h5py",
    "mkl",
    "mkl-service"
]

[project.optional-dependencies]
dev = [
    "pytest-timeout",
    "fairscale",
    "flake8",
]

[project.urls]
"Homepage" = "https://github.com/labstructbioinf/pLM-BLAST"
"Bug Tracker" = "https://github.com/labstructbioinf/pLM-BLAST/issues"

[project.scripts]
plmblast = "plmblast:main"
embeddings = "embeddings:main"
pbmanager = "plmblast_aliases:main"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = [
    "--maxfail=10", 
]
python_files = "test_*"
pythonpath = ["."]
testpaths = [
    "tests",
]
markers = [
    "embedding: marks tests as slow (deselect with '-m \"not embedding\"') requires gpu",
    "core: test functionalities of `plmblast.py`",
]

[tool.pytest_env]
PLMBLAST_DB_NPY = "~/tmp"

