import pandas as pd

seq1 = {
'info' : 'sp|Q5SM60|RSMA_THET8 Ribosomal RNA small subunit methyltransferase A',
'seq': "MSKLASPQSVRALLERHGLFADKRFGQNFLVSEAHLRRIVEAARPFTGPVFEVGPGLGALTRALLEAGAEVTAIEKDLRLRPVLEETLSGLPVRLVFQDALLYPWEEVPQGSLLVANLPYHIATPLVTRLLKTGRFARLVFLVQKEVAERMTARPKTPAYGVLTLRVAHHAVAERLFDLPPGAFFPPPKVWSSLVRLTPTGALDDPGLFRLVEAAFGKRRKTLLNALAAAGYPKARVEEALRALGLPPRVRAEELDLEAFRRLREGLEGAV"
}
seq2 = {
    'info' : 'sp|P61889|MDH_ECOLI Malate dehydrogenase OS=Escherichia coli',
    'seq' : """MKVAVLGAAGGIGQALALLLKTQLPSGSELSLYDIAPVTPGVAVDLSHIPTAVKIKGFSG
EDATPALEGADVVLISAGVARKPGMDRSDLFNVNAGIVKNLVQQVAKTCPKACIGIITNP
VNTTVAIAAEVLKKAGVYDKNKLFGVTTLDIIRSNTFVAELKGKQPGEVEVPVIGGHSGV
TILPLLSQVPGVSFTEQEVADLTKRIQNAGTEVVEAKAGGGSATLSMGQAAARFGLSLVR
ALQGEQGVVECAYVEGDGQYARFFSQPLLLGKNGVEERKSIGTLSAFEQNALEGMLDTLK
KDIALGEEFVNK"""
}

seq3 = {
    "info" : "sp|P08165|ADRO_BOVIN NADPH:adrenodoxin oxidoreductase, mitochondrial OS=Bos taurus OX=9913 GN=FDXR PE=1 SV=3",
"seq": """MAPRCWRWWPWSSWTRTRLPPSRSIQNFGQHFSTQEQTPQICVVGSGPAGFYTAQHLLKH
HSRAHVDIYEKQLVPFGLVRFGVAPDHPEVKNVINTFTQTARSDRCAFYGNVEVGRDVTV
QELQDAYHAVVLSYGAEDHQALDIPGEELPGVFSARAFVGWYNGLPENRELAPDLSCDTA
VILGQGNVALDVARILLTPPDHLEKTDITEAALGALRQSRVKTVWIVGRRGPLQVAFTIK
ELREMIQLPGTRPMLDPADFLGLQDRIKEAARPRKRLMELLLRTATEKPGVEEAARRASA
SRAWGLRFFRSPQQVLPSPDGRRAAGIRLAVTRLEGIGEATRAVPTGDVEDLPCGLVLSS
IGYKSRPIDPSVPFDPKLGVVPNMEGRVVDVPGLYCSGWVKRGPTGVITTTMTDSFLTGQ
ILLQDLKAGHLPSGPRPGSAFIKALLDSRGVWPVSFSDWEKLDAEEVSRGQASGKPREKL
LDPQEMLRLLGH"""
}

seq4 = {
    "info": "sp|P61889|MDH_ECOLI Malate dehydrogenase OS=Escherichia coli (strain K12) OX=83333 GN=mdh PE=1 SV=1",
"seq" : """MKVAVLGAAGGIGQALALLLKTQLPSGSELSLYDIAPVTPGVAVDLSHIPTAVKIKGFSG
EDATPALEGADVVLISAGVARKPGMDRSDLFNVNAGIVKNLVQQVAKTCPKACIGIITNP
VNTTVAIAAEVLKKAGVYDKNKLFGVTTLDIIRSNTFVAELKGKQPGEVEVPVIGGHSGV
TILPLLSQVPGVSFTEQEVADLTKRIQNAGTEVVEAKAGGGSATLSMGQAAARFGLSLVR
ALQGEQGVVECAYVEGDGQYARFFSQPLLLGKNGVEERKSIGTLSAFEQNALEGMLDTLK
KDIALGEEFVNK"""
}

data_list = [seq1, seq2, seq3, seq4]
df = pd.DataFrame(data_list)
df['pair'] = [1, 1, 2, 2]
df.to_csv("example_seq.csv", index=False)