name: "flow check"

on: [push]
  
jobs:
  build-linux:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: install environment
      run:  $CONDA/bin/conda  env create -f environment.yml
    - name: Tests
      run: |
        conda install pytest
        $CONDA/bin/pytest