name: "flow check"

on: push

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.2.0
      with:
        auto-activate-base: true
        python-version: 3.9
    - name: Conda info
      shell: bash -el {0}
      run: conda info
    - name: install environment
      run:  $CONDA/bin/conda  env create -f environment.yml
    - name: Tests
      run: |
        conda install pytest
        $CONDA/bin/pytest