name: "build"

on: push

jobs:
  build:
    runs-on: self-hosted
    # not ignore bash profile files
    steps:
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.2.0
      with:
        miniconda-version: "latest"
        auto-update-conda: true
        activate-environment: plmblast3
        environment-file: environment.yml
    - name: list environments
      run: conda env list
    - name: Conda info
      run: |
        pwd
        echo "$CONDA"
        which python
        conda info
    - name: Pytest run
      run: |
        conda install pytest numpy
        python -m pytest
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path--to-lcov: coverage.xml