name: "CI-CD"

on:
  push:
    branches:
     - dev
jobs:
  build:
    runs-on: self-hosted
    # not ignore bash profile files
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt
    - run: python -m pytest

    