name: "CI-CD"

on:
  push:
    branches:
     - dev
jobs:
  build:
    runs-on: self-hosted
    # not ignore bash profile files
    steps:
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.2.0
      with:
        miniconda-version: "latest"
        python-version: 3.10
    - name: list environments
      run: conda env list
    - name: install requirements
      run: pip install -r requirements.txt
    - name: Pytest run
      run: python -m pytest
    