name: "flow check"

on: push

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.2.0
      with:
        miniconda-version: "latest"
    - name: Conda info
      shell: bash -el {0}
      run: conda info
    - name: install anaconda environment
      run: |
        conda remove --name plmblast3 --all
        conda env create -f environment.yml
    - name: list environments
      run: conda env list
    - name: Pytest run
      run: |
        conda init bash
        conda activate plmblast3
        conda install pytest
        python -m pytest