name: "build"

on:
  push:
    branches:
     - dev

jobs:
  build:
    runs-on: self-hosted
    # not ignore bash profile files
    steps:
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.2.0
      with:
        miniconda-version: "latest"
        python-version: 3.9
    - name: list environments
      run: conda env list
    - name: run lint
      run: |
        conda install flake8
        flake8 --ignore=E1,E23,W503,W292,W293 alntools/
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path--to-lcov: coverage.xml
    - name: Pytest run
      run: |
        conda env update --file environment.yml
        conda install pytest
        python -m pytest
    