name: "flow check"

on: push

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.2.0
      with:
        miniconda-version: "latest"
    - name: Conda info
      shell: bash -el {0}
      run: conda info
    - name: install environment
      run:  $CONDA/bin/conda  env create -f environment.yml
    - name: Tests
      run: |
        conda activate plmblast3
        conda install pytest
        python -m pytest