name: CI-CD

on:
  push:
    branches:
     - dev

env:
  PLMBLAST_TESTDATA: /data/test_data
  PLMBLAST_DB: /data/ecod30db_mini
  PLMBLAST_WORKERS: 4

jobs:
  build:
    runs-on: self-hosted
    # not ignore bash profile files
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies
    - run: |
        pip install -r requirements.txt
        pip install -r requirements_dev.txt
    - name: run tests
      run: pytest tests/test_script.py

    