name: "build"

on: push

jobs:
  build:
    runs-on: self-hosted
    # not ignore bash profile files
    steps:
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.2.0
      with:
        miniconda-version: "lastest"
    - name: list environments
      run: conda env list
    - name: Conda info
      run: |
        pwd
        echo "$CONDA"
        which python
        conda info
    - name: run lint
      run: |
        conda env update --file environment.yml
        conda activate plmblast3
        conda install flake8
        flake8 alntools/
    - name: Pytest run
      run: |
        conda install pytest
        python -m pytest
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path--to-lcov: coverage.xml